import type { Metadata } from "next";
import Link from "next/link";

const pages: Record<string, { title: string; intro: string; signs: string[]; process: string[] }> = {
  "ac-repair": { title: "Air-conditioning repair", intro: "When cooling is interrupted, ACM provides a clear diagnosis and practical repair path for your home or business.", signs: ["Warm air from vents", "Unusual sounds or frequent cycling", "Water near your indoor unit"], process: ["Listen to the concern and inspect the system", "Explain the findings in straightforward terms", "Complete the approved repair and review next steps"] },
  "ac-installation": { title: "AC installation & replacement", intro: "ACM helps you plan a system replacement around your space, comfort goals, and long-term needs.", signs: ["Frequent repair needs", "Uneven comfort", "A system no longer meeting your needs"], process: ["Review the property and existing equipment", "Discuss appropriate options", "Coordinate an organized installation"] },
  "ac-maintenance": { title: "AC maintenance", intro: "Seasonal HVAC care helps spot small concerns before they become interruptions to your comfort.", signs: ["It has been a season since your last visit", "Airflow has changed", "Drain or filter concerns"], process: ["Inspect key system components", "Check filters, drains, and thermostat operation", "Share a simple maintenance summary"] },
  "heat-pump-services": { title: "Heat-pump services", intro: "ACM services heat-pump systems with the same thoughtful, clear communication used across every visit.", signs: ["Inconsistent heating or cooling", "Ice around the outdoor unit", "Unexpected system cycling"], process: ["Inspect operation and controls", "Identify the cause", "Recommend a focused repair or service plan"] },
  "indoor-air-quality": { title: "Indoor air quality", intro: "A more comfortable indoor environment starts with understanding airflow, filtration, and your specific concerns.", signs: ["Persistent dust", "Stuffy rooms", "Comfort concerns around airflow"], process: ["Discuss your indoor environment", "Assess practical options", "Recommend solutions that fit the space"] },
  thermostats: { title: "Thermostats", intro: "Upgrade the way you manage comfort with a thermostat setup that is easy to understand and use.", signs: ["Inaccurate temperature readings", "An outdated control", "A schedule that no longer fits your routine"], process: ["Confirm system compatibility", "Install and configure the control", "Walk through the features with you"] },
  ductwork: { title: "Ductwork", intro: "Ductwork inspection and repair can help address airflow concerns throughout a property.", signs: ["Rooms that do not cool evenly", "Weak airflow", "Visible duct damage"], process: ["Inspect accessible ductwork", "Explain observed airflow concerns", "Recommend appropriate repair options"] },
  "commercial-hvac": { title: "Commercial HVAC", intro: "Responsive HVAC support for offices, retail locations, restaurants, small commercial properties, and property managers.", signs: ["Disruptions to the customer or staff environment", "Inconsistent temperatures", "A need for recurring maintenance"], process: ["Understand the property’s priorities", "Assess the system and schedule needs", "Build a clear service or maintenance path"] },
};

export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> { const { slug } = await params; const page = pages[slug]; return { title: page?.title ?? "ACM", description: page?.intro }; }

export default async function DetailPage({ params }: { params: Promise<{ slug: string }> }) { const { slug } = await params; if (slug === "about-acm") return <Generic title="Family-owned HVAC, done right." eyebrow="ABOUT ACM" body="ACM Pure Life Services LLC is a family-owned HVAC company serving Florida homes and light commercial properties, backed by 10 years of hands-on experience in the trade. The focus is simple: honest diagnostics, clear communication, and careful repairs and installations on every call." />; if (slug === "maintenance-plans") return <Generic title="Maintenance that works around you." eyebrow="MAINTENANCE PLANS" body="ACM’s maintenance plan details are designed to be flexible as the business grows. Seasonal system inspections, filter checks, drain-line inspections, thermostat testing, electrical-component inspections, priority scheduling, and reminders can all be tailored to your property." />; if (slug === "payments") return <Generic title="A secure way to pay." eyebrow="ONLINE PAYMENTS" body="Use ACM’s payment portal for invoices, deposits, balances, or service charges once online payments have been enabled by the owner." />; const page = pages[slug] ?? pages["ac-repair"]; return <main className="detail"><header className="detail-header"><Link href="/" className="detail-logo">ACM <small>PURE LIFE SERVICES</small></Link><Link href="/#request" className="detail-cta">Request service →</Link></header><section className="detail-hero"><p>{page.title.toUpperCase()}</p><h1>{page.title}<em>Clear care. Reliable comfort.</em></h1><div><a href="tel:+19542784733">Call (954) 278-4733</a><Link href="/#request">Request service →</Link></div></section><section className="detail-grid"><article><h2>How ACM can help</h2><p>{page.intro}</p><h3>Common warning signs</h3><ul>{page.signs.map(x => <li key={x}>{x}</li>)}</ul></article><article className="process"><h2>What to expect</h2>{page.process.map((x,i) => <p key={x}><b>0{i+1}</b>{x}</p>)}<Link href="/#request">Start a service request →</Link></article></section><section className="detail-faq"><p>FREQUENTLY ASKED QUESTIONS</p><h2>Questions, answered simply.</h2><details><summary>Can I request service online?</summary><p>Yes. Send ACM a service request and include a description of the concern. The team will follow up using the contact information you provide.</p></details><details><summary>Does ACM serve homes and businesses?</summary><p>Yes. ACM supports residential customers and light commercial properties.</p></details><details><summary>How do I pay an invoice?</summary><p>Use the online payment area after ACM has enabled its secure payment provider.</p></details></section><footer className="detail-footer">ACM Pure Life Services LLC · Family-Owned HVAC Service · <a href="tel:+19542784733">(954) 278-4733</a></footer></main>; }
function Generic({ title, eyebrow, body }: {title:string;eyebrow:string;body:string}) { return <main className="generic"><Link href="/" className="detail-logo">ACM <small>PURE LIFE SERVICES</small></Link><p>{eyebrow}</p><h1>{title}</h1><div>{body}</div><Link href="/#request">Request HVAC service →</Link></main> }
